<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="1" failed="2" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-11-16T20:53:10 CST" name="Suite" finished-at="2022-11-16T20:54:03 CST" duration-ms="53202">
    <groups>
    </groups>
    <test started-at="2022-11-16T20:53:10 CST" name="Error Validation Test" finished-at="2022-11-16T20:53:34 CST" duration-ms="24103">
      <class name="Ahmad.PersonalFramework.test.ErrorValidation">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Ahmad.PersonalFramework.test.ErrorValidation@5e2c3d18]" started-at="2022-11-16T20:53:10 CST" name="launchApplication" finished-at="2022-11-16T20:53:23 CST" duration-ms="13275" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:Ahmad.PersonalFramework.test.ErrorValidation@5e2c3d18]" started-at="2022-11-16T20:53:23 CST" name="LoginErrorValidation" finished-at="2022-11-16T20:53:24 CST" duration-ms="1245" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Ahmad.PersonalFramework.test.ErrorValidation@5e2c3d18]" started-at="2022-11-16T20:53:24 CST" name="tearDown" finished-at="2022-11-16T20:53:25 CST" duration-ms="347" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Ahmad.PersonalFramework.test.ErrorValidation@5e2c3d18]" started-at="2022-11-16T20:53:25 CST" name="launchApplication" finished-at="2022-11-16T20:53:32 CST" duration-ms="7031" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductErrorValidation()[pri:0, instance:Ahmad.PersonalFramework.test.ErrorValidation@5e2c3d18]" started-at="2022-11-16T20:53:32 CST" name="ProductErrorValidation" finished-at="2022-11-16T20:53:34 CST" duration-ms="1918" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at AhmadPersonalFramework.PageObjects.ProductCataloguePage.addProductToCart(ProductCataloguePage.java:50)
at Ahmad.PersonalFramework.test.ErrorValidation.ProductErrorValidation(ErrorValidation.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:471)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Ahmad.PersonalFramework.test.ErrorValidation@5e2c3d18]" started-at="2022-11-16T20:53:34 CST" name="tearDown" finished-at="2022-11-16T20:53:34 CST" duration-ms="124" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Ahmad.PersonalFramework.test.ErrorValidation -->
    </test> <!-- Error Validation Test -->
    <test started-at="2022-11-16T20:53:10 CST" name="Submit Order Test" finished-at="2022-11-16T20:54:03 CST" duration-ms="53202">
      <class name="Ahmad.PersonalFramework.test.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Ahmad.PersonalFramework.test.SubmitOrderTest@4d5650ae]" started-at="2022-11-16T20:53:10 CST" name="launchApplication" finished-at="2022-11-16T20:53:21 CST" duration-ms="11684" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder()[pri:0, instance:Ahmad.PersonalFramework.test.SubmitOrderTest@4d5650ae]" started-at="2022-11-16T20:53:21 CST" name="submitOrder" finished-at="2022-11-16T20:53:47 CST" duration-ms="25093" status="FAIL">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at Ahmad.PersonalFramework.test.SubmitOrderTest.submitOrder(SubmitOrderTest.java:47)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:471)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Ahmad.PersonalFramework.test.SubmitOrderTest@4d5650ae]" started-at="2022-11-16T20:53:47 CST" name="tearDown" finished-at="2022-11-16T20:54:03 CST" duration-ms="16283" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:Ahmad.PersonalFramework.test.SubmitOrderTest@4d5650ae]" started-at="2022-11-16T20:54:03 CST" name="OrderHistoryTest" finished-at="2022-11-16T20:54:03 CST" depends-on-methods="Ahmad.PersonalFramework.test.SubmitOrderTest.submitOrder" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Ahmad.PersonalFramework.test.SubmitOrderTest.OrderHistoryTest() on instance Ahmad.PersonalFramework.test.SubmitOrderTest@4d5650ae depends on not successfully finished methods 
[Ahmad.PersonalFramework.test.SubmitOrderTest.submitOrder() on instance Ahmad.PersonalFramework.test.SubmitOrderTest@4d5650ae]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Ahmad.PersonalFramework.test.SubmitOrderTest.OrderHistoryTest() on instance Ahmad.PersonalFramework.test.SubmitOrderTest@4d5650ae depends on not successfully finished methods 
[Ahmad.PersonalFramework.test.SubmitOrderTest.submitOrder() on instance Ahmad.PersonalFramework.test.SubmitOrderTest@4d5650ae]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:150)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:471)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
      </class> <!-- Ahmad.PersonalFramework.test.SubmitOrderTest -->
    </test> <!-- Submit Order Test -->
  </suite> <!-- Suite -->
</testng-results>
