<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="1" failed="2" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-11-15T22:47:55 CST" name="Suite" finished-at="2022-11-15T22:48:30 CST" duration-ms="34509">
    <groups>
    </groups>
    <test started-at="2022-11-15T22:47:55 CST" name="Error Validation Test" finished-at="2022-11-15T22:48:13 CST" duration-ms="17785">
      <class name="Ahmad.PersonalFramework.test.ErrorValidation">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Ahmad.PersonalFramework.test.ErrorValidation@1c5920df]" started-at="2022-11-15T22:47:55 CST" name="launchApplication" finished-at="2022-11-15T22:48:05 CST" duration-ms="9525" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:Ahmad.PersonalFramework.test.ErrorValidation@1c5920df]" started-at="2022-11-15T22:48:05 CST" name="LoginErrorValidation" finished-at="2022-11-15T22:48:05 CST" duration-ms="869" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Ahmad.PersonalFramework.test.ErrorValidation@1c5920df]" started-at="2022-11-15T22:48:05 CST" name="tearDown" finished-at="2022-11-15T22:48:06 CST" duration-ms="304" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Ahmad.PersonalFramework.test.ErrorValidation@1c5920df]" started-at="2022-11-15T22:48:06 CST" name="launchApplication" finished-at="2022-11-15T22:48:11 CST" duration-ms="5598" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductErrorValidation()[pri:0, instance:Ahmad.PersonalFramework.test.ErrorValidation@1c5920df]" started-at="2022-11-15T22:48:11 CST" name="ProductErrorValidation" finished-at="2022-11-15T22:48:13 CST" duration-ms="1296" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "prod" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "prod" is null
at AhmadPersonalFramework.PageObjects.ProductCataloguePage.addProductToCart(ProductCataloguePage.java:50)
at Ahmad.PersonalFramework.test.ErrorValidation.ProductErrorValidation(ErrorValidation.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:471)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Ahmad.PersonalFramework.test.ErrorValidation@1c5920df]" started-at="2022-11-15T22:48:13 CST" name="tearDown" finished-at="2022-11-15T22:48:13 CST" duration-ms="121" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Ahmad.PersonalFramework.test.ErrorValidation -->
    </test> <!-- Error Validation Test -->
    <test started-at="2022-11-15T22:47:55 CST" name="Submit Order Test" finished-at="2022-11-15T22:48:30 CST" duration-ms="34508">
      <class name="Ahmad.PersonalFramework.test.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Ahmad.PersonalFramework.test.SubmitOrderTest@73e9cf30]" started-at="2022-11-15T22:47:55 CST" name="launchApplication" finished-at="2022-11-15T22:48:05 CST" duration-ms="9774" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder()[pri:0, instance:Ahmad.PersonalFramework.test.SubmitOrderTest@73e9cf30]" started-at="2022-11-15T22:48:05 CST" name="submitOrder" finished-at="2022-11-15T22:48:29 CST" duration-ms="24494" status="FAIL">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at Ahmad.PersonalFramework.test.SubmitOrderTest.submitOrder(SubmitOrderTest.java:47)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:471)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Ahmad.PersonalFramework.test.SubmitOrderTest@73e9cf30]" started-at="2022-11-15T22:48:29 CST" name="tearDown" finished-at="2022-11-15T22:48:29 CST" duration-ms="140" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:Ahmad.PersonalFramework.test.SubmitOrderTest@73e9cf30]" started-at="2022-11-15T22:48:29 CST" name="OrderHistoryTest" finished-at="2022-11-15T22:48:29 CST" depends-on-methods="Ahmad.PersonalFramework.test.SubmitOrderTest.submitOrder" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Ahmad.PersonalFramework.test.SubmitOrderTest.OrderHistoryTest() on instance Ahmad.PersonalFramework.test.SubmitOrderTest@73e9cf30 depends on not successfully finished methods 
[Ahmad.PersonalFramework.test.SubmitOrderTest.submitOrder() on instance Ahmad.PersonalFramework.test.SubmitOrderTest@73e9cf30]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Ahmad.PersonalFramework.test.SubmitOrderTest.OrderHistoryTest() on instance Ahmad.PersonalFramework.test.SubmitOrderTest@73e9cf30 depends on not successfully finished methods 
[Ahmad.PersonalFramework.test.SubmitOrderTest.submitOrder() on instance Ahmad.PersonalFramework.test.SubmitOrderTest@73e9cf30]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:150)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:471)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
      </class> <!-- Ahmad.PersonalFramework.test.SubmitOrderTest -->
    </test> <!-- Submit Order Test -->
  </suite> <!-- Suite -->
</testng-results>
